services:
  postgres-beautique:
    image: postgres:16
    hostname: postgres-beautique
    environment:
      POSTGRES_DB: beautique
      POSTGRES_USER: beautique
      POSTGRES_PASSWORD: beautique
    volumes:
      - 'C:/Users/Rafael/Documents/db-beautique/db-beautique:/var/lib/postgresql/data'
      - ./init-beautique-schema.sql:/docker-entrypoint-initdb.d/init-beautique-schema.sql
    ports:
      - '3334:5432'
    networks:
      - beautique-network
  rabbitmq:
    image: 'rabbitmq:3-management'
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports: 
      - '5672:5672'
      - '15672:15672'
    networks:
      - beautique-network
    volumes:
      - 'C:/Users/Rafael/Documents/rabbitmq-data:/var/lib/rabbitmq'
      - 'C:/Users/Rafael/Documents/rabbitmq-log:/var/lib/rabbitmq'
  mongodb:
    image: 'mongo:latest'
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    volumes:
      - 'C:/Users/Rafael/Documents/db-mongo-db:/data/db'
      - './mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh'
    ports:
      - '27017:27017'
    networks:
      - beautique-network

networks:
  beautique-network:
    driver: bridge